/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignInRouteImport } from './routes/signIn'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as AuthIndexRouteImport } from './routes/_auth/index'
import { Route as AuthVisitorsRouteImport } from './routes/_auth/visitors'
import { Route as AuthSettingsRouteImport } from './routes/_auth/settings'
import { Route as AuthCheckInRouteImport } from './routes/_auth/check-in'
import { Route as AuthAdminsRouteImport } from './routes/_auth/admins'

const SignInRoute = SignInRouteImport.update({
  id: '/signIn',
  path: '/signIn',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthIndexRoute = AuthIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthVisitorsRoute = AuthVisitorsRouteImport.update({
  id: '/visitors',
  path: '/visitors',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSettingsRoute = AuthSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthRoute,
} as any)
const AuthCheckInRoute = AuthCheckInRouteImport.update({
  id: '/check-in',
  path: '/check-in',
  getParentRoute: () => AuthRoute,
} as any)
const AuthAdminsRoute = AuthAdminsRouteImport.update({
  id: '/admins',
  path: '/admins',
  getParentRoute: () => AuthRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthIndexRoute
  '/signIn': typeof SignInRoute
  '/admins': typeof AuthAdminsRoute
  '/check-in': typeof AuthCheckInRoute
  '/settings': typeof AuthSettingsRoute
  '/visitors': typeof AuthVisitorsRoute
}
export interface FileRoutesByTo {
  '/signIn': typeof SignInRoute
  '/admins': typeof AuthAdminsRoute
  '/check-in': typeof AuthCheckInRoute
  '/settings': typeof AuthSettingsRoute
  '/visitors': typeof AuthVisitorsRoute
  '/': typeof AuthIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_auth': typeof AuthRouteWithChildren
  '/signIn': typeof SignInRoute
  '/_auth/admins': typeof AuthAdminsRoute
  '/_auth/check-in': typeof AuthCheckInRoute
  '/_auth/settings': typeof AuthSettingsRoute
  '/_auth/visitors': typeof AuthVisitorsRoute
  '/_auth/': typeof AuthIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/signIn'
    | '/admins'
    | '/check-in'
    | '/settings'
    | '/visitors'
  fileRoutesByTo: FileRoutesByTo
  to: '/signIn' | '/admins' | '/check-in' | '/settings' | '/visitors' | '/'
  id:
    | '__root__'
    | '/_auth'
    | '/signIn'
    | '/_auth/admins'
    | '/_auth/check-in'
    | '/_auth/settings'
    | '/_auth/visitors'
    | '/_auth/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthRoute: typeof AuthRouteWithChildren
  SignInRoute: typeof SignInRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signIn': {
      id: '/signIn'
      path: '/signIn'
      fullPath: '/signIn'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/': {
      id: '/_auth/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/visitors': {
      id: '/_auth/visitors'
      path: '/visitors'
      fullPath: '/visitors'
      preLoaderRoute: typeof AuthVisitorsRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/settings': {
      id: '/_auth/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthSettingsRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/check-in': {
      id: '/_auth/check-in'
      path: '/check-in'
      fullPath: '/check-in'
      preLoaderRoute: typeof AuthCheckInRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/admins': {
      id: '/_auth/admins'
      path: '/admins'
      fullPath: '/admins'
      preLoaderRoute: typeof AuthAdminsRouteImport
      parentRoute: typeof AuthRoute
    }
  }
}

interface AuthRouteChildren {
  AuthAdminsRoute: typeof AuthAdminsRoute
  AuthCheckInRoute: typeof AuthCheckInRoute
  AuthSettingsRoute: typeof AuthSettingsRoute
  AuthVisitorsRoute: typeof AuthVisitorsRoute
  AuthIndexRoute: typeof AuthIndexRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthAdminsRoute: AuthAdminsRoute,
  AuthCheckInRoute: AuthCheckInRoute,
  AuthSettingsRoute: AuthSettingsRoute,
  AuthVisitorsRoute: AuthVisitorsRoute,
  AuthIndexRoute: AuthIndexRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthRoute: AuthRouteWithChildren,
  SignInRoute: SignInRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
